name: Release Chart Auto

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
      - release-*
    paths:
      - 'addons/falkordb/**'

jobs:
  release-chart:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release-chart.yml
    permissions:
      contents: write
      packages: write
